//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRessourcesP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUREAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUREAU()
        {
            this.DEMANDER = new HashSet<DEMANDER>();
        }
    
        public int ID_BUREAU { get; set; }
        public string CODE_BUREAU { get; set; }
        public string LIBELLE_BUREAU { get; set; }
        public string SUPERFICIE_BUREAU { get; set; }
        public int ID_PALIER { get; set; }
        public Nullable<int> ID_SITE { get; set; }
    
        public virtual PALIER PALIER { get; set; }
        public virtual SITE SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEMANDER> DEMANDER { get; set; }
    }
}
