//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRessourcesP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_RESSOURCESPEntities : DbContext
    {
        public DB_RESSOURCESPEntities()
            : base("name=DB_RESSOURCESPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENT { get; set; }
        public virtual DbSet<BUREAU> BUREAU { get; set; }
        public virtual DbSet<DEMANDER> DEMANDER { get; set; }
        public virtual DbSet<MOBILIER> MOBILIER { get; set; }
        public virtual DbSet<PALIER> PALIER { get; set; }
        public virtual DbSet<SITE> SITE { get; set; }
        public virtual DbSet<SOLLICITER> SOLLICITER { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    
        public virtual ObjectResult<SP_BAC_GET_BUREAU_Result> SP_BAC_GET_BUREAU(string cODE_BUREAU, string lIBELLE_BUREAU, string sUPERFICIE_BUREAU, Nullable<int> iD_PALIER, Nullable<int> iD_SITE)
        {
            var cODE_BUREAUParameter = cODE_BUREAU != null ?
                new ObjectParameter("CODE_BUREAU", cODE_BUREAU) :
                new ObjectParameter("CODE_BUREAU", typeof(string));
    
            var lIBELLE_BUREAUParameter = lIBELLE_BUREAU != null ?
                new ObjectParameter("LIBELLE_BUREAU", lIBELLE_BUREAU) :
                new ObjectParameter("LIBELLE_BUREAU", typeof(string));
    
            var sUPERFICIE_BUREAUParameter = sUPERFICIE_BUREAU != null ?
                new ObjectParameter("SUPERFICIE_BUREAU", sUPERFICIE_BUREAU) :
                new ObjectParameter("SUPERFICIE_BUREAU", typeof(string));
    
            var iD_PALIERParameter = iD_PALIER.HasValue ?
                new ObjectParameter("ID_PALIER", iD_PALIER) :
                new ObjectParameter("ID_PALIER", typeof(int));
    
            var iD_SITEParameter = iD_SITE.HasValue ?
                new ObjectParameter("ID_SITE", iD_SITE) :
                new ObjectParameter("ID_SITE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BAC_GET_BUREAU_Result>("SP_BAC_GET_BUREAU", cODE_BUREAUParameter, lIBELLE_BUREAUParameter, sUPERFICIE_BUREAUParameter, iD_PALIERParameter, iD_SITEParameter);
        }
    
        public virtual ObjectResult<SP_BAC_PL_GET_DEMANDER_DETAILS_REPORTING_Result> SP_BAC_PL_GET_DEMANDER_DETAILS_REPORTING(string mATRICULE_AGENT, Nullable<int> cODE_BUREAU)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            var cODE_BUREAUParameter = cODE_BUREAU.HasValue ?
                new ObjectParameter("CODE_BUREAU", cODE_BUREAU) :
                new ObjectParameter("CODE_BUREAU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BAC_PL_GET_DEMANDER_DETAILS_REPORTING_Result>("SP_BAC_PL_GET_DEMANDER_DETAILS_REPORTING", mATRICULE_AGENTParameter, cODE_BUREAUParameter);
        }
    
        public virtual ObjectResult<SP_BAC_PL_GET_SOLLICITER_DETAILS_REPORTING_Result> SP_BAC_PL_GET_SOLLICITER_DETAILS_REPORTING(string mATRICULE_AGENT, Nullable<int> cODE_MOBILIER)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            var cODE_MOBILIERParameter = cODE_MOBILIER.HasValue ?
                new ObjectParameter("CODE_MOBILIER", cODE_MOBILIER) :
                new ObjectParameter("CODE_MOBILIER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BAC_PL_GET_SOLLICITER_DETAILS_REPORTING_Result>("SP_BAC_PL_GET_SOLLICITER_DETAILS_REPORTING", mATRICULE_AGENTParameter, cODE_MOBILIERParameter);
        }
    
        public virtual ObjectResult<SP_GET_AGENT_DEMANDER_Result> SP_GET_AGENT_DEMANDER(string mATRICULE_AGENT)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_AGENT_DEMANDER_Result>("SP_GET_AGENT_DEMANDER", mATRICULE_AGENTParameter);
        }
    
        public virtual ObjectResult<SP_GET_AGENT_SOLLICITER_Result> SP_GET_AGENT_SOLLICITER(string mATRICULE_AGENT)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_AGENT_SOLLICITER_Result>("SP_GET_AGENT_SOLLICITER", mATRICULE_AGENTParameter);
        }
    
        public virtual ObjectResult<SP_GET_DEMANDER_ENVOYE_Result> SP_GET_DEMANDER_ENVOYE(string mATRICULE_AGENT, string cODE_BUREAU)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            var cODE_BUREAUParameter = cODE_BUREAU != null ?
                new ObjectParameter("CODE_BUREAU", cODE_BUREAU) :
                new ObjectParameter("CODE_BUREAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_DEMANDER_ENVOYE_Result>("SP_GET_DEMANDER_ENVOYE", mATRICULE_AGENTParameter, cODE_BUREAUParameter);
        }
    
        public virtual ObjectResult<SP_GET_SOLLICITER_ENVOYE_Result> SP_GET_SOLLICITER_ENVOYE(string mATRICULE_AGENT, string cODE_MOBILIER)
        {
            var mATRICULE_AGENTParameter = mATRICULE_AGENT != null ?
                new ObjectParameter("MATRICULE_AGENT", mATRICULE_AGENT) :
                new ObjectParameter("MATRICULE_AGENT", typeof(string));
    
            var cODE_MOBILIERParameter = cODE_MOBILIER != null ?
                new ObjectParameter("CODE_MOBILIER", cODE_MOBILIER) :
                new ObjectParameter("CODE_MOBILIER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SOLLICITER_ENVOYE_Result>("SP_GET_SOLLICITER_ENVOYE", mATRICULE_AGENTParameter, cODE_MOBILIERParameter);
        }
    
        public virtual ObjectResult<SP_SEC_LOGIN_Result> SP_SEC_LOGIN(string lOG, string mDP)
        {
            var lOGParameter = lOG != null ?
                new ObjectParameter("LOG", lOG) :
                new ObjectParameter("LOG", typeof(string));
    
            var mDPParameter = mDP != null ?
                new ObjectParameter("MDP", mDP) :
                new ObjectParameter("MDP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEC_LOGIN_Result>("SP_SEC_LOGIN", lOGParameter, mDPParameter);
        }
    
        public virtual int SP_UPDATE_RESERVER(Nullable<int> iD_DEMANDER, string sTATUT_DEMANDER)
        {
            var iD_DEMANDERParameter = iD_DEMANDER.HasValue ?
                new ObjectParameter("ID_DEMANDER", iD_DEMANDER) :
                new ObjectParameter("ID_DEMANDER", typeof(int));
    
            var sTATUT_DEMANDERParameter = sTATUT_DEMANDER != null ?
                new ObjectParameter("STATUT_DEMANDER", sTATUT_DEMANDER) :
                new ObjectParameter("STATUT_DEMANDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RESERVER", iD_DEMANDERParameter, sTATUT_DEMANDERParameter);
        }
    
        public virtual int SP_UPDATE_SOLLICITER(Nullable<int> iD_SOLLICITER, string sTATUT_SOLLICITER)
        {
            var iD_SOLLICITERParameter = iD_SOLLICITER.HasValue ?
                new ObjectParameter("ID_SOLLICITER", iD_SOLLICITER) :
                new ObjectParameter("ID_SOLLICITER", typeof(int));
    
            var sTATUT_SOLLICITERParameter = sTATUT_SOLLICITER != null ?
                new ObjectParameter("STATUT_SOLLICITER", sTATUT_SOLLICITER) :
                new ObjectParameter("STATUT_SOLLICITER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_SOLLICITER", iD_SOLLICITERParameter, sTATUT_SOLLICITERParameter);
        }
    }
}
