//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRessourcesP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBILIER()
        {
            this.SOLLICITER = new HashSet<SOLLICITER>();
        }
    
        public int ID_MOBILIER { get; set; }
        public string CODE_MOBILIER { get; set; }
        public string LIBELLE_MOBILIER { get; set; }
        public string MARQUE_MOBILIER { get; set; }
        public string MODELE_MOBILIER { get; set; }
        public string NUMSERIE_MOBILIER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLLICITER> SOLLICITER { get; set; }
    }
}
