//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRessourcesP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLLICITER
    {
        public int ID_SOLLICITER { get; set; }
        public int ID_AGENT { get; set; }
        public int ID_MOBILIER { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
        public string OBJET_REUNION { get; set; }
        public Nullable<System.DateTime> DATE_RETOUR { get; set; }
        public string MOTIF_RETOUR { get; set; }
        public string STATUT_SOLLICITER { get; set; }
        public Nullable<System.DateTime> DATE_EMISSION { get; set; }
        public Nullable<System.DateTime> DATE_TRAITEMENT { get; set; }
        public string STATUT_REPORT { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual MOBILIER MOBILIER { get; set; }
    }
}
